/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Denzel Ovando
 */
public class Vista_Menu extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public Vista_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Fondo = new javax.swing.JPanel();
        PanelBarraSuperior = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        BarraInferior = new javax.swing.JPanel();
        lblBienvenida2 = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        btnCatalogos = new javax.swing.JButton();
        btnCatSucursal = new javax.swing.JButton();
        btnCatEmpleados = new javax.swing.JButton();
        btnCatClientes = new javax.swing.JButton();
        btnCatProductos = new javax.swing.JButton();
        btnCatGastos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnVenPuntoVen = new javax.swing.JButton();
        btnVenFacturas = new javax.swing.JButton();
        btnVenPedidos = new javax.swing.JButton();
        btnVenCotizacion = new javax.swing.JButton();
        btnVenAlmacen = new javax.swing.JButton();
        btnProduccion = new javax.swing.JButton();
        btnAdministrativo = new javax.swing.JButton();
        btnAdminCuentasPagar = new javax.swing.JButton();
        btnAdminNomina = new javax.swing.JButton();
        btnAdminGastos = new javax.swing.JButton();
        btnAdminEfectivo = new javax.swing.JButton();
        btnAdminChequeo = new javax.swing.JButton();
        btnAdminCompras = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnInvCompras = new javax.swing.JButton();
        btnInvAlmacenes = new javax.swing.JButton();
        btnRecursosHumanos = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PanelBarraSuperior.setBackground(new java.awt.Color(158, 95, 50));
        PanelBarraSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(158, 95, 50)));

        btnSalir.setBackground(new java.awt.Color(158, 95, 50));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconSalir.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnSalir.setIconTextGap(5);

        btnMenu.setBackground(new java.awt.Color(158, 95, 50));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconDrawer.png"))); // NOI18N
        btnMenu.setText("  Panaderia Malpica   ");
        btnMenu.setBorder(null);
        btnMenu.setFocusPainted(false);
        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnMenu.setIconTextGap(5);
        btnMenu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout PanelBarraSuperiorLayout = new javax.swing.GroupLayout(PanelBarraSuperior);
        PanelBarraSuperior.setLayout(PanelBarraSuperiorLayout);
        PanelBarraSuperiorLayout.setHorizontalGroup(
            PanelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBarraSuperiorLayout.createSequentialGroup()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelBarraSuperiorLayout.setVerticalGroup(
            PanelBarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        BarraInferior.setBackground(new java.awt.Color(58, 70, 68));
        BarraInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBienvenida2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblBienvenida2.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconUser.png"))); // NOI18N
        lblBienvenida2.setText("Bienvenido, Username !");
        lblBienvenida2.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout BarraInferiorLayout = new javax.swing.GroupLayout(BarraInferior);
        BarraInferior.setLayout(BarraInferiorLayout);
        BarraInferiorLayout.setHorizontalGroup(
            BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BarraInferiorLayout.createSequentialGroup()
                .addContainerGap(990, Short.MAX_VALUE)
                .addComponent(lblBienvenida2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        BarraInferiorLayout.setVerticalGroup(
            BarraInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBienvenida2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        NavBar.setBackground(new java.awt.Color(240, 209, 160));
        NavBar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), java.awt.Color.gray));
        NavBar.setLayout(new java.awt.GridBagLayout());

        btnCatalogos.setBackground(new java.awt.Color(238, 192, 123));
        btnCatalogos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnCatalogos.setForeground(new java.awt.Color(102, 102, 102));
        btnCatalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnCatalogos.setText("Catálogos ");
        btnCatalogos.setAlignmentY(0.0F);
        btnCatalogos.setBorder(null);
        btnCatalogos.setBorderPainted(false);
        btnCatalogos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogos.setFocusPainted(false);
        btnCatalogos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatalogos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCatalogos.setIconTextGap(5);
        btnCatalogos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCatalogos.setMaximumSize(new java.awt.Dimension(159, 25));
        btnCatalogos.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        NavBar.add(btnCatalogos, gridBagConstraints);

        btnCatSucursal.setBackground(new java.awt.Color(240, 209, 160));
        btnCatSucursal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCatSucursal.setForeground(new java.awt.Color(102, 102, 102));
        btnCatSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnCatSucursal.setText("Sucursal");
        btnCatSucursal.setAlignmentY(0.0F);
        btnCatSucursal.setBorder(null);
        btnCatSucursal.setBorderPainted(false);
        btnCatSucursal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatSucursal.setFocusPainted(false);
        btnCatSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatSucursal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCatSucursal.setIconTextGap(5);
        btnCatSucursal.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCatSucursal.setMaximumSize(new java.awt.Dimension(159, 25));
        btnCatSucursal.setMinimumSize(new java.awt.Dimension(159, 25));
        btnCatSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatSucursalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnCatSucursal, gridBagConstraints);

        btnCatEmpleados.setBackground(new java.awt.Color(240, 209, 160));
        btnCatEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCatEmpleados.setForeground(new java.awt.Color(102, 102, 102));
        btnCatEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnCatEmpleados.setText("Empleados");
        btnCatEmpleados.setAlignmentY(0.0F);
        btnCatEmpleados.setBorder(null);
        btnCatEmpleados.setBorderPainted(false);
        btnCatEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatEmpleados.setFocusPainted(false);
        btnCatEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCatEmpleados.setIconTextGap(5);
        btnCatEmpleados.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCatEmpleados.setMaximumSize(new java.awt.Dimension(159, 25));
        btnCatEmpleados.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnCatEmpleados, gridBagConstraints);

        btnCatClientes.setBackground(new java.awt.Color(240, 209, 160));
        btnCatClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCatClientes.setForeground(new java.awt.Color(102, 102, 102));
        btnCatClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnCatClientes.setText("Clientes");
        btnCatClientes.setAlignmentY(0.0F);
        btnCatClientes.setBorder(null);
        btnCatClientes.setBorderPainted(false);
        btnCatClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatClientes.setFocusPainted(false);
        btnCatClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCatClientes.setIconTextGap(5);
        btnCatClientes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCatClientes.setMaximumSize(new java.awt.Dimension(159, 25));
        btnCatClientes.setMinimumSize(new java.awt.Dimension(159, 25));
        btnCatClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnCatClientes, gridBagConstraints);

        btnCatProductos.setBackground(new java.awt.Color(240, 209, 160));
        btnCatProductos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCatProductos.setForeground(new java.awt.Color(102, 102, 102));
        btnCatProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnCatProductos.setText("Productos");
        btnCatProductos.setAlignmentY(0.0F);
        btnCatProductos.setBorder(null);
        btnCatProductos.setBorderPainted(false);
        btnCatProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatProductos.setFocusPainted(false);
        btnCatProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatProductos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCatProductos.setIconTextGap(5);
        btnCatProductos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCatProductos.setMaximumSize(new java.awt.Dimension(159, 25));
        btnCatProductos.setMinimumSize(new java.awt.Dimension(159, 25));
        btnCatProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatProductosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnCatProductos, gridBagConstraints);

        btnCatGastos.setBackground(new java.awt.Color(240, 209, 160));
        btnCatGastos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCatGastos.setForeground(new java.awt.Color(102, 102, 102));
        btnCatGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnCatGastos.setText("Gastos");
        btnCatGastos.setAlignmentY(0.0F);
        btnCatGastos.setBorder(null);
        btnCatGastos.setBorderPainted(false);
        btnCatGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatGastos.setFocusPainted(false);
        btnCatGastos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCatGastos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCatGastos.setIconTextGap(5);
        btnCatGastos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCatGastos.setMaximumSize(new java.awt.Dimension(159, 25));
        btnCatGastos.setMinimumSize(new java.awt.Dimension(159, 25));
        btnCatGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatGastosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnCatGastos, gridBagConstraints);

        btnVentas.setBackground(new java.awt.Color(238, 192, 123));
        btnVentas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(102, 102, 102));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setActionCommand("Producción");
        btnVentas.setAlignmentY(0.0F);
        btnVentas.setBorder(null);
        btnVentas.setBorderPainted(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.setFocusPainted(false);
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVentas.setIconTextGap(5);
        btnVentas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVentas.setMaximumSize(new java.awt.Dimension(159, 25));
        btnVentas.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        NavBar.add(btnVentas, gridBagConstraints);

        btnVenPuntoVen.setBackground(new java.awt.Color(240, 209, 160));
        btnVenPuntoVen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVenPuntoVen.setForeground(new java.awt.Color(102, 102, 102));
        btnVenPuntoVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnVenPuntoVen.setText("Punto de Venta");
        btnVenPuntoVen.setAlignmentY(0.0F);
        btnVenPuntoVen.setBorder(null);
        btnVenPuntoVen.setBorderPainted(false);
        btnVenPuntoVen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenPuntoVen.setFocusPainted(false);
        btnVenPuntoVen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenPuntoVen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenPuntoVen.setIconTextGap(5);
        btnVenPuntoVen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVenPuntoVen.setMaximumSize(new java.awt.Dimension(159, 25));
        btnVenPuntoVen.setMinimumSize(new java.awt.Dimension(159, 25));
        btnVenPuntoVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenPuntoVenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnVenPuntoVen, gridBagConstraints);

        btnVenFacturas.setBackground(new java.awt.Color(240, 209, 160));
        btnVenFacturas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVenFacturas.setForeground(new java.awt.Color(102, 102, 102));
        btnVenFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnVenFacturas.setText("Factura de Ventas");
        btnVenFacturas.setAlignmentY(0.0F);
        btnVenFacturas.setBorder(null);
        btnVenFacturas.setBorderPainted(false);
        btnVenFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenFacturas.setFocusPainted(false);
        btnVenFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenFacturas.setIconTextGap(5);
        btnVenFacturas.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVenFacturas.setMaximumSize(new java.awt.Dimension(159, 25));
        btnVenFacturas.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnVenFacturas, gridBagConstraints);

        btnVenPedidos.setBackground(new java.awt.Color(240, 209, 160));
        btnVenPedidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVenPedidos.setForeground(new java.awt.Color(102, 102, 102));
        btnVenPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnVenPedidos.setText("Pedidos");
        btnVenPedidos.setAlignmentY(0.0F);
        btnVenPedidos.setBorder(null);
        btnVenPedidos.setBorderPainted(false);
        btnVenPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenPedidos.setFocusPainted(false);
        btnVenPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenPedidos.setIconTextGap(5);
        btnVenPedidos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVenPedidos.setMaximumSize(new java.awt.Dimension(159, 25));
        btnVenPedidos.setMinimumSize(new java.awt.Dimension(159, 25));
        btnVenPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenPedidosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnVenPedidos, gridBagConstraints);

        btnVenCotizacion.setBackground(new java.awt.Color(240, 209, 160));
        btnVenCotizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVenCotizacion.setForeground(new java.awt.Color(102, 102, 102));
        btnVenCotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnVenCotizacion.setText("Cotización");
        btnVenCotizacion.setAlignmentY(0.0F);
        btnVenCotizacion.setBorder(null);
        btnVenCotizacion.setBorderPainted(false);
        btnVenCotizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenCotizacion.setFocusPainted(false);
        btnVenCotizacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenCotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenCotizacion.setIconTextGap(5);
        btnVenCotizacion.setMargin(new java.awt.Insets(0, 10, 0, 0));
        btnVenCotizacion.setMaximumSize(new java.awt.Dimension(159, 25));
        btnVenCotizacion.setMinimumSize(new java.awt.Dimension(159, 25));
        btnVenCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenCotizacionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnVenCotizacion, gridBagConstraints);

        btnVenAlmacen.setBackground(new java.awt.Color(240, 209, 160));
        btnVenAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVenAlmacen.setForeground(new java.awt.Color(102, 102, 102));
        btnVenAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnVenAlmacen.setText("Monto de almacén");
        btnVenAlmacen.setAlignmentY(0.0F);
        btnVenAlmacen.setBorder(null);
        btnVenAlmacen.setBorderPainted(false);
        btnVenAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVenAlmacen.setFocusPainted(false);
        btnVenAlmacen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVenAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenAlmacen.setIconTextGap(5);
        btnVenAlmacen.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnVenAlmacen.setMaximumSize(new java.awt.Dimension(159, 25));
        btnVenAlmacen.setMinimumSize(new java.awt.Dimension(159, 25));
        btnVenAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenAlmacenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnVenAlmacen, gridBagConstraints);

        btnProduccion.setBackground(new java.awt.Color(238, 192, 123));
        btnProduccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnProduccion.setForeground(new java.awt.Color(102, 102, 102));
        btnProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnProduccion.setText("Producción");
        btnProduccion.setAlignmentY(0.0F);
        btnProduccion.setBorder(null);
        btnProduccion.setBorderPainted(false);
        btnProduccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduccion.setFocusPainted(false);
        btnProduccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProduccion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProduccion.setIconTextGap(5);
        btnProduccion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnProduccion.setMaximumSize(new java.awt.Dimension(159, 25));
        btnProduccion.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        NavBar.add(btnProduccion, gridBagConstraints);

        btnAdministrativo.setBackground(new java.awt.Color(238, 192, 123));
        btnAdministrativo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnAdministrativo.setForeground(new java.awt.Color(102, 102, 102));
        btnAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdministrativo.setText("Administrativo");
        btnAdministrativo.setAlignmentY(0.0F);
        btnAdministrativo.setBorder(null);
        btnAdministrativo.setBorderPainted(false);
        btnAdministrativo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrativo.setFocusPainted(false);
        btnAdministrativo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdministrativo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdministrativo.setIconTextGap(5);
        btnAdministrativo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdministrativo.setMaximumSize(new java.awt.Dimension(159, 25));
        btnAdministrativo.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        NavBar.add(btnAdministrativo, gridBagConstraints);

        btnAdminCuentasPagar.setBackground(new java.awt.Color(240, 209, 160));
        btnAdminCuentasPagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminCuentasPagar.setForeground(new java.awt.Color(102, 102, 102));
        btnAdminCuentasPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdminCuentasPagar.setText("Cuentas por Pagar");
        btnAdminCuentasPagar.setAlignmentY(0.0F);
        btnAdminCuentasPagar.setBorder(null);
        btnAdminCuentasPagar.setBorderPainted(false);
        btnAdminCuentasPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminCuentasPagar.setFocusPainted(false);
        btnAdminCuentasPagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminCuentasPagar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminCuentasPagar.setIconTextGap(5);
        btnAdminCuentasPagar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminCuentasPagar.setMaximumSize(new java.awt.Dimension(159, 25));
        btnAdminCuentasPagar.setMinimumSize(new java.awt.Dimension(159, 25));
        btnAdminCuentasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCuentasPagarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnAdminCuentasPagar, gridBagConstraints);

        btnAdminNomina.setBackground(new java.awt.Color(240, 209, 160));
        btnAdminNomina.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminNomina.setForeground(new java.awt.Color(102, 102, 102));
        btnAdminNomina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdminNomina.setText("Nomina");
        btnAdminNomina.setAlignmentY(0.0F);
        btnAdminNomina.setBorder(null);
        btnAdminNomina.setBorderPainted(false);
        btnAdminNomina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminNomina.setFocusPainted(false);
        btnAdminNomina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminNomina.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminNomina.setIconTextGap(5);
        btnAdminNomina.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminNomina.setMaximumSize(new java.awt.Dimension(159, 25));
        btnAdminNomina.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnAdminNomina, gridBagConstraints);

        btnAdminGastos.setBackground(new java.awt.Color(240, 209, 160));
        btnAdminGastos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminGastos.setForeground(new java.awt.Color(102, 102, 102));
        btnAdminGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdminGastos.setText("Gastos");
        btnAdminGastos.setAlignmentY(0.0F);
        btnAdminGastos.setBorder(null);
        btnAdminGastos.setBorderPainted(false);
        btnAdminGastos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminGastos.setFocusPainted(false);
        btnAdminGastos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminGastos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminGastos.setIconTextGap(5);
        btnAdminGastos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminGastos.setMaximumSize(new java.awt.Dimension(159, 25));
        btnAdminGastos.setMinimumSize(new java.awt.Dimension(159, 25));
        btnAdminGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminGastosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnAdminGastos, gridBagConstraints);

        btnAdminEfectivo.setBackground(new java.awt.Color(240, 209, 160));
        btnAdminEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminEfectivo.setForeground(new java.awt.Color(102, 102, 102));
        btnAdminEfectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdminEfectivo.setText("Manejo en efectivo");
        btnAdminEfectivo.setAlignmentY(0.0F);
        btnAdminEfectivo.setBorder(null);
        btnAdminEfectivo.setBorderPainted(false);
        btnAdminEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminEfectivo.setFocusPainted(false);
        btnAdminEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminEfectivo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminEfectivo.setIconTextGap(5);
        btnAdminEfectivo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminEfectivo.setMaximumSize(new java.awt.Dimension(159, 25));
        btnAdminEfectivo.setMinimumSize(new java.awt.Dimension(159, 25));
        btnAdminEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminEfectivoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnAdminEfectivo, gridBagConstraints);

        btnAdminChequeo.setBackground(new java.awt.Color(240, 209, 160));
        btnAdminChequeo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminChequeo.setForeground(new java.awt.Color(102, 102, 102));
        btnAdminChequeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdminChequeo.setText("Chequeo en efectivo");
        btnAdminChequeo.setAlignmentY(0.0F);
        btnAdminChequeo.setBorder(null);
        btnAdminChequeo.setBorderPainted(false);
        btnAdminChequeo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminChequeo.setFocusPainted(false);
        btnAdminChequeo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminChequeo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminChequeo.setIconTextGap(5);
        btnAdminChequeo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminChequeo.setMaximumSize(new java.awt.Dimension(159, 25));
        btnAdminChequeo.setMinimumSize(new java.awt.Dimension(159, 25));
        btnAdminChequeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminChequeoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnAdminChequeo, gridBagConstraints);

        btnAdminCompras.setBackground(new java.awt.Color(240, 209, 160));
        btnAdminCompras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdminCompras.setForeground(new java.awt.Color(102, 102, 102));
        btnAdminCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnAdminCompras.setText("Factura de Compras");
        btnAdminCompras.setAlignmentY(0.0F);
        btnAdminCompras.setBorder(null);
        btnAdminCompras.setBorderPainted(false);
        btnAdminCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdminCompras.setFocusPainted(false);
        btnAdminCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdminCompras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAdminCompras.setIconTextGap(5);
        btnAdminCompras.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdminCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminComprasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnAdminCompras, gridBagConstraints);

        btnInventario.setBackground(new java.awt.Color(238, 192, 123));
        btnInventario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(102, 102, 102));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnInventario.setText("Inventario");
        btnInventario.setAlignmentY(0.0F);
        btnInventario.setBorder(null);
        btnInventario.setBorderPainted(false);
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventario.setFocusPainted(false);
        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInventario.setIconTextGap(5);
        btnInventario.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnInventario.setMaximumSize(new java.awt.Dimension(159, 25));
        btnInventario.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        NavBar.add(btnInventario, gridBagConstraints);

        btnInvCompras.setBackground(new java.awt.Color(240, 209, 160));
        btnInvCompras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInvCompras.setForeground(new java.awt.Color(102, 102, 102));
        btnInvCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnInvCompras.setText("Compras");
        btnInvCompras.setAlignmentY(0.0F);
        btnInvCompras.setBorder(null);
        btnInvCompras.setBorderPainted(false);
        btnInvCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvCompras.setFocusPainted(false);
        btnInvCompras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInvCompras.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInvCompras.setIconTextGap(5);
        btnInvCompras.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnInvCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvComprasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnInvCompras, gridBagConstraints);

        btnInvAlmacenes.setBackground(new java.awt.Color(240, 209, 160));
        btnInvAlmacenes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInvAlmacenes.setForeground(new java.awt.Color(102, 102, 102));
        btnInvAlmacenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnInvAlmacenes.setText("Almacenes");
        btnInvAlmacenes.setAlignmentY(0.0F);
        btnInvAlmacenes.setBorder(null);
        btnInvAlmacenes.setBorderPainted(false);
        btnInvAlmacenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInvAlmacenes.setFocusPainted(false);
        btnInvAlmacenes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInvAlmacenes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInvAlmacenes.setIconTextGap(5);
        btnInvAlmacenes.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnInvAlmacenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvAlmacenesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        NavBar.add(btnInvAlmacenes, gridBagConstraints);

        btnRecursosHumanos.setBackground(new java.awt.Color(238, 192, 123));
        btnRecursosHumanos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnRecursosHumanos.setForeground(new java.awt.Color(102, 102, 102));
        btnRecursosHumanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/iconModule.png"))); // NOI18N
        btnRecursosHumanos.setText("Recursos humanos");
        btnRecursosHumanos.setAlignmentY(0.0F);
        btnRecursosHumanos.setBorder(null);
        btnRecursosHumanos.setBorderPainted(false);
        btnRecursosHumanos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecursosHumanos.setFocusPainted(false);
        btnRecursosHumanos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRecursosHumanos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRecursosHumanos.setIconTextGap(5);
        btnRecursosHumanos.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRecursosHumanos.setMaximumSize(new java.awt.Dimension(159, 25));
        btnRecursosHumanos.setMinimumSize(new java.awt.Dimension(159, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        NavBar.add(btnRecursosHumanos, gridBagConstraints);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(BarraInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(PanelBarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, 656, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(BarraInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCatGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatGastosActionPerformed

    private void btnCatProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatProductosActionPerformed

    private void btnCatClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatClientesActionPerformed

    private void btnCatSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCatSucursalActionPerformed

    private void btnAdminCuentasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCuentasPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCuentasPagarActionPerformed

    private void btnAdminGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminGastosActionPerformed

    private void btnAdminEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminEfectivoActionPerformed

    private void btnAdminChequeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminChequeoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminChequeoActionPerformed

    private void btnAdminComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminComprasActionPerformed

    private void btnVenPuntoVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenPuntoVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenPuntoVenActionPerformed

    private void btnVenPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenPedidosActionPerformed

    private void btnVenCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenCotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenCotizacionActionPerformed

    private void btnVenAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenAlmacenActionPerformed

    private void btnInvComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInvComprasActionPerformed

    private void btnInvAlmacenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvAlmacenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInvAlmacenesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraInferior;
    private javax.swing.JPanel Fondo;
    public javax.swing.JPanel NavBar;
    private javax.swing.JPanel PanelBarraSuperior;
    public javax.swing.JButton btnAdminChequeo;
    public javax.swing.JButton btnAdminCompras;
    public javax.swing.JButton btnAdminCuentasPagar;
    public javax.swing.JButton btnAdminEfectivo;
    public javax.swing.JButton btnAdminGastos;
    public javax.swing.JButton btnAdminNomina;
    public javax.swing.JButton btnAdministrativo;
    public javax.swing.JButton btnCatClientes;
    public javax.swing.JButton btnCatEmpleados;
    public javax.swing.JButton btnCatGastos;
    public javax.swing.JButton btnCatProductos;
    public javax.swing.JButton btnCatSucursal;
    public javax.swing.JButton btnCatalogos;
    public javax.swing.JButton btnInvAlmacenes;
    public javax.swing.JButton btnInvCompras;
    public javax.swing.JButton btnInventario;
    public javax.swing.JButton btnMenu;
    public javax.swing.JButton btnProduccion;
    public javax.swing.JButton btnRecursosHumanos;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnVenAlmacen;
    public javax.swing.JButton btnVenCotizacion;
    public javax.swing.JButton btnVenFacturas;
    public javax.swing.JButton btnVenPedidos;
    public javax.swing.JButton btnVenPuntoVen;
    public javax.swing.JButton btnVentas;
    public javax.swing.JLabel lblBienvenida2;
    public javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
